runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: "2.5.2"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always

- url: /scripts
  static_dir: dist/static/scripts
  secure: always

- url: /bower_components
  static_dir: dist/static/bower_components
  secure: always

- url: /assets
  static_dir: assets
  secure: always

- url: /dist
  static_dir: dist
  secure: always

- url: /.well-known/(.*)
  script: le.app

- url: .*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?bower\.json
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?node_modules/.*
- ^(.*/)?tests/.*
- ^.*.md|markdown
